config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :categories
  #   resources :courses, as: :courses
  # resources :news, as: :news
  # end
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: :rails_admin

  get ':category_slug/news/:id', controller: :news, action: :show, as: :news
  get ':category_slug/course/:id', controller: :courses, action: :show, as: :course
  get ':category_slug/course/', controller: :courses, action: :index, as: :courses

  resources :modules_course_image, controller: 'ckeditor_pictures'
  devise_for :users, as: :frontend
end

app/views/partials/_footer.html.haml
/ End Sponsors Style Two
/ Main Footer
%footer.main-footer
  .container
    .main_footer
      .row
        .col-lg-4.col-md-4.col-sm-6.col-xs-12.footer_logo
          %figure
            %a{:href => "index.html"}
              %img{:alt => "logo", :src => image_path("logo-2.png")}/
          .icon-list
            .item
              %h6 ADDRESS:
              %a{:href => "#"}
                %span 100A Cologne Universtiy, United States
              %a{:href => "#"}
                %i.flaticon-web-page-home
            .item
              %h6 MAIL:
              %a{:href => "#"}
                %span cologneuniverstiy@support.com
              %a{:href => "#"}
                %i.flaticon-envelope
            .item
              %h6 PHONE:
              %a{:href => "#"}
                %span (+1) 90 - 800 - 7990 , (+1) 90 - 802 - 7390
              %a{:href => "#"}
                %i.flaticon-phone-call
        .col-lg-3.col-md-3.col-sm-6.col-xs-12.quick_links
          %h5 TWITTER FEED
          .links-list
            .item
              %h6
                The Love Boat soon will be making
                = succeed "another" do
                  %br/
              %a{:href => "#"}
                %span http:///D:/Font%20&%20Icons/Icon
              %a.tran3s{:href => "#"}
                %i.fa.fa-twitter
            .item
              %h6
                The Love Boat soon will be making
                = succeed "another" do
                  %br/
              %a{:href => "#"}
                %span http:///D:/%20&%20Icons/Icon
              %a.tran3s{:href => "#"}
                %i.fa.fa-twitter
            .item
              %h6 The Love Boat soon will be making
              %a{:href => "#"}
                %span http:///D:/Font%20&%20
              %a.tran3s{:href => "#"}
                %i.fa.fa-twitter
        .col-lg-2.col-md-2.col-sm-6.col-xs-12.recent_news_footer
          %h5 EXPLORE
          %ul.others-link
            %li
              %i.fa.fa-life-ring{"aria-hidden" => "true"}
              %a{:href => "#"} Accounting
            %li
              %i.fa.fa-life-ring{"aria-hidden" => "true"}
              %a{:href => "#"} Business
            %li
              %i.fa.fa-life-ring{"aria-hidden" => "true"}
              %a{:href => "#"} Economics
            %li
              %i.fa.fa-life-ring{"aria-hidden" => "true"}
              %a{:href => "#"} Finance
            %li
              %i.fa.fa-life-ring{"aria-hidden" => "true"}
              %a{:href => "#"} Management
            %li
              %i.fa.fa-life-ring{"aria-hidden" => "true"}
              %a{:href => "#"} Robotics
            %li
              %i.fa.fa-life-ring{"aria-hidden" => "true"}
              %a{:href => "#"} Technologies
        .col-lg-3.col-md-3.col-sm-6.col-xs-12.footer_gallery
          %h5 PHOTO STREAM
          %h6 The Love Boat soon will be making run
          .image-gallery
            .row
              .col-md-4.col-sm-4.col-xs-2
                .image-box
                  %figure
                    %a{:href => "#"}
                      %img{:alt => "", :src => image_path("footer/1.jpg")}/
              .col-md-4.col-sm-4.col-xs-2
                .image-box
                  %figure
                    %a{:href => "#"}
                      %img{:alt => "", :src => image_path("footer/2.jpg")}/
              .col-md-4.col-sm-4.col-xs-2
                .image-box
                  %figure
                    %a{:href => "#"}
                      %img{:alt => "", :src => image_path("footer/3.jpg")}/
              .col-md-4.col-sm-4.col-xs-2
                .image-box
                  %figure
                    %a{:href => "#"}
                      %img{:alt => "", :src => image_path("footer/4.jpg")}/
              .col-md-4.col-sm-4.col-xs-2
                .image-box
                  %figure
                    %a{:href => "#"}
                      %img{:alt => "", :src => image_path("footer/5.jpg")}/
              .col-md-4.col-sm-4.col-xs-2
                .image-box
                  %figure
                    %a{:href => "#"}
                      %img{:alt => "", :src => image_path("footer/6.jpg")}/
    / End of .footer_contact
    .bottom-bg
      .bottom_footer.clearfix
        %p.pull-left.font_fix
          = "© Copyright anglo-connect.com #{DateTime.now.strftime('%Y')}. All Rights Reserved"
        %ul.social-links
          %li
            %a.tran3s{:href => "#", :title => "Facebook"}
              %i.fa.fa-facebook{"aria-hidden" => "true"}
          %li
            %a.tran3s{:href => "#", :title => "Twitter"}
              %i.fa.fa-twitter{"aria-hidden" => "true"}
          %li
            %a.tran3s{:href => "#", :title => "Linkedin"}
              %i.fa.fa-linkedin{"aria-hidden" => "true"}
          %li
            %a.tran3s{:href => "#", :title => "Goolge-Plus"}
              %i.fa.fa-google-plus{"aria-hidden" => "true"}
          %li
            %a.tran3s{:href => "#", :title => "pinterest-p"}
              %i.fa.fa-pinterest-p{"aria-hidden" => "true"}
        .clear_fix
/ Main Footer
/ End pagewrapper
/ Scroll to top
.scroll-to-top.scroll-to-target{"data-target" => ".main-header"}
  %span.icon.fa.fa-long-arrow-up
/ Gallery Popup
#gallery-popup.gallery-box
  / Bg Fade Layer
  .bg-fade-layer
  .popup-container
    .popup-content
      .popup-header
        %button.btn-close
          %span.fa.fa-close
        %h3 our gallery
      .content-outer
        / Vertical Slider
        .vertical-slider
          / template
          .ms-vertical-template.ms-tabs-vertical-template{:style => "position: relative;"}
            / masterslider
            #masterslider.master-slider.ms-skin-default.ms-wk{:style => "visibility: visible; opacity: 1; margin: 0px;"}
              .ms-container
                .ms-inner-controls-cont{:style => "max-width: 850px;"}
                  .ms-view.ms-basic-view.ms-grab-cursor{:style => "width: 835px; height: 461.706px;"}
                    .ms-slide-container{:style => "transform: translateY(0px) translateZ(0px);"}
                      .ms-slide.ms-sl-selected{:style => "width: 835px; height: 461.706px; top: 0px;"}
                        .ms-slide-bgcont{:style => "height: 100%; opacity: 1;"}
                          %img{:alt => "", :src => image_path("gallery/1.jpg"), :style => "width: 835px; height: 631.892px; margin-top: -85px; margin-left: 0px;"}/
                      .ms-slide{:style => "width: 835px; height: 461.706px; top: 471.706px;"}
                        .ms-slide-bgcont{:style => "height: 100%; opacity: 1;"}
                          %img{:alt => "", :src => image_path("gallery/2.jpg"), :style => "width: 835px; height: 631.892px; margin-top: -85px; margin-left: 0px;"}/
                      .ms-slide{:style => "width: 835px; height: 461.706px; top: 943.412px;"}
                        .ms-slide-bgcont{:style => "height: 100%; opacity: 1;"}
                          %img{:alt => "", :src => image_path("gallery/3.jpg"), :style => "width: 835px; height: 631.892px; margin-top: -85px; margin-left: 0px;"}/
                      .ms-slide{:style => "width: 835px; height: 461.706px; top: 1415.12px;"}
                        .ms-slide-bgcont{:style => "height: 100%; opacity: 1;"}
                          %img{:alt => "", :src => image_path("gallery/4.jpg"), :style => "width: 835px; height: 631.892px; margin-top: -85px; margin-left: 0px;"}/
                      .ms-slide{:style => "width: 835px; height: 461.706px; top: 1886.82px;"}
                        .ms-slide-bgcont{:style => "height: 100%; opacity: 1;"}
                          %img{:alt => "", :src => image_path("gallery/5.jpg"), :style => "width: 835px; height: 631.892px; margin-top: -85px; margin-left: 0px;"}/
                      .ms-slide{:style => "width: 835px; height: 461.706px; top: 2358.53px;"}
                        .ms-slide-bgcont{:style => "height: 100%; opacity: 1;"}
                          %img{:alt => "", :src => image_path("gallery/6.jpg"), :style => "width: 835px; height: 631.892px; margin-top: -85px; margin-left: 0px;"}/
                      .ms-slide{:style => "width: 835px; height: 461.706px; top: 2830.24px;"}
                        .ms-slide-bgcont{:style => "height: 100%; opacity: 1;"}
                          %img{:alt => "", :src => image_path("gallery/7.jpg"), :style => "width: 835px; height: 519.054px; margin-top: -28.5px; margin-left: 0px;"}/
                      .ms-slide{:style => "width: 835px; height: 461.706px; top: 3301.94px;"}
                        .ms-slide-bgcont{:style => "height: 100%; opacity: 1;"}
                          %img{:alt => "", :src => image_path("gallery/8.jpg"), :style => "width: 835px; height: 519.054px; margin-top: -28.5px; margin-left: 0px;"}/
                  .ms-nav-next{:style => "opacity: 0; display: none;"}
                  .ms-nav-prev{:style => "opacity: 0; display: none;"}
                  .ms-ctimer
                    %canvas.ms-ctimer-canvas{:height => "17", :width => "17"}
                    .ms-ctimer-bullet
              .ms-sbar.ms-dir-v
                .ms-bar{:style => "width: 4px; background-color: rgb(61, 61, 61); height: 61.8043px; opacity: 0;"}
              .ms-thumb-list.ms-dir-v
                .ms-thumbs-cont{:style => "height: 856px;"}
                  .ms-thumb-frame.ms-thumb-frame-selected
                    %img.ms-thumb{:alt => "thumb", :src => image_path("gallery/1.jpg")}/
                    .ms-thumb-ol
                  .ms-thumb-frame
                    %img.ms-thumb{:alt => "thumb", :src => image_path("gallery/2.jpg")}/
                    .ms-thumb-ol
                  .ms-thumb-frame
                    %img.ms-thumb{:alt => "thumb", :src => image_path("gallery/3.jpg")}/
                    .ms-thumb-ol
                  .ms-thumb-frame
                    %img.ms-thumb{:alt => "thumb", :src => image_path("gallery/4.jpg")}/
                    .ms-thumb-ol
                  .ms-thumb-frame
                    %img.ms-thumb{:alt => "thumb", :src => image_path("gallery/5.jpg")}/
                    .ms-thumb-ol
                  .ms-thumb-frame
                    %img.ms-thumb{:alt => "thumb", :src => image_path("gallery/6.jpg")}/
                    .ms-thumb-ol
                  .ms-thumb-frame
                    %img.ms-thumb{:alt => "thumb", :src => image_path("gallery/7.jpg")}/
                    .ms-thumb-ol
                  .ms-thumb-frame
                    %img.ms-thumb{:alt => "thumb", :src => image_path("gallery/8.jpg")}/
                    .ms-thumb-ol
/ end of masterslider
/ end of template
/ popup-content
/ popup-container
/ Gallery Box
= javascript_include_tag "jquery-2.1.4"
= javascript_include_tag  "bootstrap.min"
= javascript_include_tag "jquery.themepunch.tools.min"
= javascript_include_tag "jquery.themepunch.revolution.min"
= javascript_include_tag "revolution.extension.slideanims.min"
= javascript_include_tag "revolution.extension.layeranimation.min"
= javascript_include_tag "revolution.extension.navigation.min"
= javascript_include_tag "revolution.extension.kenburn.min"
= javascript_include_tag "revolution.extension.actions.min"
= javascript_include_tag "revolution.extension.parallax.min"
= javascript_include_tag "revolution.extension.migration.min"
= javascript_include_tag "jquery.fancybox.pack"
= javascript_include_tag "jquery-ui.min"
/ owl.carousel
= javascript_include_tag "owl.carousel.min"
/ js count to
= javascript_include_tag "jquery.appear"
= javascript_include_tag "jquery.countTo"
= javascript_include_tag "isotope"
= javascript_include_tag "jquery.fancybox.pack"
= javascript_include_tag "jquery.fancybox-media"
= javascript_include_tag "owl"
= javascript_include_tag "masterslider"
= javascript_include_tag "jquery.polyglot.language.switcher"
= javascript_include_tag "owl.carousel.min"
= javascript_include_tag "jquery.mixitup.min"
= javascript_include_tag "validate"
= javascript_include_tag "wow"
= javascript_include_tag "script"
/ Theme js _________
= javascript_include_tag "theme"
/ End of .page_wrapper

app/views/partials/_header.html.haml
%header.main-header
  / Main Header
  .header-upper
    .container
      .header-upper-bg.clearfix
        .main-logo.pull-left
          %figure
            = link_to root_path do
              = image_tag 'logo.png'
        .top-info.pull-right
          %ul
            %li.single-info-box
              .icon-holder
                %span.flaticon-phone-call
              .text-holder
                %p
                  = "+38 /057/ 706 00 38"
                  %br
                  = "+38 /099/ 924 32 43"
                  %br
                  = "+38 /050/ 992 43 40"
            %li.single-info-box
              .icon-holder
                %span.flaticon-envelope
              .text-holder
                = mail_to 'angloconnect.com@gmail.com' do
                  %p
                    %span EMAIL:
                    = succeed 'angloconnect.com@gmail.com' do
                      %br/
            %li.single-info-box
              .icon-holder
                %i.fa.fa-skype{aria: {hidden: true}}
              .text-holder
                = link_to 'skype:anglo.connect' do
                  %p
                    %span SKYPE:
                    = succeed 'anglo.connect' do
                      %br/
  .header-lower
    .container.menu-bg
      .row.menu-bar.clearfix
        %nav.main-menu
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          .navbar-collapse.collapse.clearfix
            %ul.navigation.clearfix
              %li
                = link_to root_path do
                  %i.fa.fa-home
                  Главная
              %li.dropdown
                %a{:href => "#"} ПРО НАС
                %ul
                  %li
                    %a{:href => "about.html"} about us
                  %li
                    %a{:href => "service.html"} Service page
                  %li
                    %a{:href => "events.html"} events
                  %li
                    %a{:href => "events-2.html"} events single
              %li.dropdown
                %a{:href => "#"} КУРСЫ
                %ul
                  %li
                    %a{:href => "course.html"} courses grid
                  %li
                    %a{:href => "course-2.html"} courses list
                  %li
                    %a{:href => "course-3.html"} courses single
              %li.dropdown
                %a{:href => "blog.html"} НОВОСТИ
                %ul
                  %li
                    %a{:href => "blog.html"} Blog Default
                  %li
                    %a{:href => "blog-2.html"} Blog Standard
                  %li
                    %a{:href => "blog-3.html"} Blog Single
              %li
                %a{:href => "contact.html"} СВЯЗЬ
        %ul.nav_right_area
          %li.search_option
            .outer-search-box
              .seach-toggle
                %i.fa.fa-search
              %ul.search-box
                %li
                  %form{:action => "index.html", :method => "post"}
                    .form-group
                      %input{:name => "search", :placeholder => "Поиск...", :required => "", :type => "search"}/
                      %button{:type => "submit"}
                        %i.fa.fa-search
          %li.login-option
            - if current_frontend_user.present?
              = link_to destroy_frontend_user_session_path, method: :delete do
                %i.flaticon-login
                %span Выход
            - else
              = link_to new_frontend_user_session_path do
                %i.flaticon-login
                %span Вход
          -#%li#polyglotLanguageSwitcher
          -#  %i.flaticon-world
          -#  %form{:action => "#"}
          -#    %select#polyglot-language-options
          -#      %option#en{:selected => "selected", :value => "en"} eng
          -#      %option#fr{:value => "fr"} Fre
          -#      %option#de{:value => "de"} Ger
          -#      %option#it{:value => "it"} Ita
          -#      %option#es{:value => "es"} Spa
  / End #polyglotLanguageSwitcher
  / Sticky Header
  .sticky-header
    .container.menu-bg
      .row.menu-bar.clearfix
        %nav.main-menu
          .navbar-header
            %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
              %span.icon-bar
              %span.icon-bar
              %span.icon-bar
          .navbar-collapse.collapse.clearfix
            %ul.navigation.clearfix
              %li.dropdown
                %a{:href => "#"}
                  %i.fa.fa-home>
                  Home
                %ul
                  %li
                    %a{:href => "index.html"} home one
                  %li
                    %a{:href => "index-2.html"} home two
                  %li
                    %a{:href => "index-3.html"} home three
              %li.dropdown
                %a{:href => "#"} about us
                %ul
                  %li
                    %a{:href => "about.html"} about us
                  %li
                    %a{:href => "service.html"} Service page
                  %li
                    %a{:href => "events.html"} events
                  %li
                    %a{:href => "events-2.html"} events single
              %li.dropdown
                %a{:href => "#"} OUR COURSES
                %ul
                  %li
                    %a{:href => "course.html"} courses grid
                  %li
                    %a{:href => "course-2.html"} courses list
                  %li
                    %a{:href => "course-3.html"} courses single
              %li
                %a{:href => "gallery.html"} GALLERY
              %li.dropdown
                %a{:href => "blog.html"} Blog
                %ul
                  %li
                    %a{:href => "blog.html"} Blog Default
                  %li
                    %a{:href => "blog-2.html"} Blog Standard
                  %li
                    %a{:href => "blog-3.html"} Blog Single
              %li
                %a{:href => "contact.html"} CONTACT US
        %ul.nav_right_area
          %li.search_option
            .outer-search-box
              .seach-toggle
                %i.fa.fa-search
              %ul.search-box
                %li
                  %form{:action => "index.html", :method => "post"}
                    .form-group
                      %input{:name => "search", :placeholder => "Search Here", :required => "", :type => "search"}/
                      %button{:type => "submit"}
                        %i.fa.fa-search
          %li.login-option
            %a{:href => "#"}
              %i.flaticon-login
              %span Sign in or Register