config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'

  resources :categories
  #   resources :courses, as: :courses
  # resources :news, as: :news
  # end
  mount Ckeditor::Engine => '/ckeditor'
  mount RailsAdmin::Engine => '/admin', as: :rails_admin

  get ':category_slug/news/:id', controller: :news, action: :show, as: :news
  get ':category_slug/course/:id', controller: :courses, action: :show, as: :course
  get ':category_slug/course/', controller: :courses, action: :index, as: :courses

  resources :modules_course_image, controller: 'ckeditor_pictures'
  devise_for :users, as: :frontend
end

app/controllers/home_controller.rb
# frozen_string_literal: true

class HomeController < ApplicationController
  def index
    @slides = Slider.for_showing
    @services = Service.includes(:icon).order('created_at DESC').limit(4)
    @courses = Course.includes(:category).where(is_main: true).decorate
    @partners = Partner.includes(:icon).order('created_at DESC').all
    @courses_categories = @courses.map { |course| { title: course.category.title, class: ".category_class_#{course.category.id}" } }.uniq
    @teachers = Teacher.order('created_at DESC').all
    render 'home/index'
  end
end

app/views/home/partials/_contact_form.html.haml
.col-md-4.col-sm-12.col-xs-12
  .comment-box
    .title-box.text-center
      %h4
        %i.flaticon-nature
        ЗАКАЗАТЬ КУРC
    .default-form-area
      %form#contact-form.default-form{:action => "inc/sendmail.php", :method => "post", :name => "contact_form", :novalidate => "novalidate"}
        .form-group
          %h6 ИМЯ
          %input.form-control{:name => "form_name", :placeholder => "Enter your Name", :required => "", :type => "text", :value => ""}/
        .form-group
          %h6 ТЕЛЕФОН
          %input.form-control.required{:name => "form_phone", :placeholder => "Enter your Phone", :required => "", :type => "phone", :value => ""}/
        .form-group
          %h6 EMAIL
          %input.form-control.required.email{:name => "form_email", :placeholder => "Enter your Email", :required => "", :type => "email", :value => ""}/
        .form-group
          %h6 КУРС
          -#=select('request', 'course_id', get_courses_list, {prompt: 'Выберите курс...'}, class: %i(text-capitalize selectpicker form-control required), data: {style: :'g-select', width: '100%'})

          -#%select.text-capitalize.selectpicker.form-control.required{"data-style" => "g-select", "data-width" => "100%", :name => "form_subject"}
          -#  %option Currency
          -#  %option Insurance
          -#  %option Finance
        .form-group
          %h6 СООБЩЕНИЕ
          %textarea.form-control.required{:name => "form_message", :placeholder => "Введите сообщение", :required => ""}
        .form-group.text-center
          %input#form_botcheck.form-control{:name => "form_botcheck", :type => "hidden", :value => ""}/
          %button.btn-style-one{"data-loading-text" => "Please wait...", :type => "submit"} Отправить запрос

app/views/home/partials/_course.html.haml
.col-lg-4.col-md-4.col-sm-12.col-xs-12.mix{"data-bound" => "", :style => "display:table-cell;", class: "category_class_#{course.category.id}"}
  .single_item
    .img_holder
      = image_tag course.main_image(:fancy), alt: course.title, class: %i(img-responsive)
      .overlay.tran3s
        .link
          = link_to course.main_image(:full_content), class: :fancybox do
            %i.flaticon-plus-symbol
    / End .overlay
    / End .img_holder
    .content
      = link_to course_path course.category, course do
        %h5
          = course.title
      -#.reting-box
                -#%i.fa.fa-star{"aria-hidden" => "true"}
                -#%i.fa.fa-star{"aria-hidden" => "true"}
                -#%i.fa.fa-star{"aria-hidden" => "true"}
                -#%i.fa.fa-star{"aria-hidden" => "true"}
                -#%i.fa.fa-star-half-o{"aria-hidden" => "true"}
      %p
        = course.short_description
      %a{:href => "course-3.html"}
        =  'ПОДРОБНО'
      .price-many
        %span
          != '&#x20b4;'
        = course.price
    / End .title
    %ul.content-text
      %li.time-duration
        %i.flaticon-time
        = "Длительность: #{course.duration} Yrs"
      %li.students
        %i.flaticon-students-cap
        = "#{course.students_count} студентов"
        / End .single_item

app/views/home/partials/_partners.html.haml
/ Sponsors Style Two
%section.sponsors-logos.style-two
  .your-logo.wow.fadeInUp
    .container
      %ul.sponsors-slider
        - @partners.each do |item|
          %li
            .image-box
              = link_to item.site_url, target: :_blank do
                = image_tag item.icon.url(:thumb)
/ End Sponsors Style Two

app/views/home/partials/_section_contact_form.html.haml
/ contact-form
%section.contact-form
  .container
    .form-widght.clearfix
      %ul.form-section.pull-left
        %li.item
          %h5 NAME
          .form-group
            %input{:name => "fname", :placeholder => "Enter your Name", :required => "", :type => "text", :value => ""}/
        %li.item
          %h5 EMAIL
          .form-group
            %input{:name => "email", :placeholder => "Enter Your Email", :required => "", :type => "email", :value => ""}/
        %li.item
          %h5 SELECT COURSE
          .form-group
            %select{:name => "subject"}
              %option Select Your Course
              %option Insurance
              %option Finance
      %li.search_option.pull-right
        .outer-search-box
          .seach-toggle
            %i.flaticon-search
          %ul.search-box
            %li
              %form{:action => "index.html", :method => "post"}
                .form-group
                  %input{:name => "search", :placeholder => "Search Here", :required => "", :type => "search"}/
                  %button{:type => "submit"}
                    %i.flaticon-search
                    / contact-form end

app/views/home/partials/_section_slider.html.haml
/ Main Slider
%section.banner
  .rev_slider_wrapper{style: 'height: 550px'}
    #main_slider.rev_slider{"data-version" => "5.0"}
      %ul
        = render partial: 'home/partials/slider_item', collection: @slides, as: :slide

app/views/home/partials/_service_section.html.haml
/ services section
%section.about-us.scroll-to-this
  .container
    .col-md-8.col-sm-12.col-xs-12
      .section-title
        %h3 НАШИ УСЛУГИ
        %p Что-то, что мы можем предложить
      - rows = @services.each_slice(2)
      - rows.with_index do |item, i|
        .row
          - item.each do |service|
            .col-md-6.col-sm-6.col-xs-12
              .item
                - if service.icon.present?
                  %figure
                    = link_to '#' do
                      = image_tag service.icon.url(:thumb)
                .content-text
                  %i.flaticon-books-stack-of-three
                  = link_to '#' do
                    %h5
                      = service.title
                  %p
                    = service.short_description
    = render partial: 'home/partials/contact_form'

app/views/home/partials/_slider_item.html.haml
%li.slide_show{class: "slide_#{slide_counter.next}", "data-description" => "", "data-easein" => "default", "data-easeout" => "default", "data-index" => "rs-35#{slide_counter.next}", "data-masterspeed" => "default", "data-rotate" => "0", "data-saveperformance" => "off", "data-slotamount" => "default", "data-title" => "Slide Boxes", "data-transition" => slide.slide_type}
  / Slide_show
  %img.rev-slidebg{:alt => "", "data-bgfit" => "cover", "data-bgposition" => "center center", "data-bgrepeat" => "no-repeat", :src => slide.slide_image.url(:gallery)}/
  .tp-caption{"data-hoffset" => "0", "data-mask_out" => "x:inherit;y:inherit;s:inherit;e:inherit;", "data-splitin" => "none", "data-splitout" => "none", "data-start" => "2000", "data-transform_idle" => "o:1;", "data-transform_in" => "z:0;rX:0deg;rY:0;rZ:0;sX:1.5;sY:1.5;skX:0;skY:0;opacity:0;s:2000;e:Power3.easeInOut;", "data-transform_out" => "y:[100%];s:1000;s:1000;", "data-voffset" => "-180", "data-whitespace" => "nowrap", "data-x" => "center", "data-y" => "center"}
  .main_heading.tp-caption.tp-resizeme{"data-hoffset" => "0", "data-mask_out" => "x:inherit;y:inherit;s:inherit;e:inherit;", "data-splitin" => "none", "data-splitout" => "none", "data-start" => "2000", "data-transform_idle" => "o:1;", "data-transform_in" => "z:0;rX:0deg;rY:0;rZ:0;sX:1.5;sY:1.5;skX:0;skY:0;opacity:0;s:2000;e:Power3.easeInOut;", "data-transform_out" => "y:[100%];s:1000;s:1000;", "data-voffset" => "-50", "data-whitespace" => "nowrap", "data-x" => "center", "data-y" => "center"}
    = link_to slide.url do
      %h1
        = slide.title.html_safe
      .slide_description
        %span
          = slide.description